### ISSUE TITLE
Clarify scope 

### ISSUE THREAD

**Issue by BigLep** [ipfs/helia-delegated-routing-v1-http-api#35]
Things that I think we should make clearer in the README:
1. Link to the "/routing/v1" API that we're implementing
2. How it relates to https://github.com/libp2p/js-http-v1-content-routing
3. What /routing/v1 IPIPs it supports (e.g.,  IPIP-417 (Delegated Peer lookups), IPIP-379 (Delegated IPNS lookups))

**Comment by BigLep** [comment]
@achingbrain : before we move on from delegated routing work for the time being, I'd like to finish this.

For example, I think showing how someone actually uses this with their Helia instance (i.e., they need to use https://github.com/libp2p/js-http-v1-content-routing ) is important.  I also want to make it clear that if there are expansions to https://specs.ipfs.tech/routing/http-routing-v1/ that in order for it to be useful for Helia client users, code changes are need in this repo and https://github.com/libp2p/js-http-v1-content-routing

**Comment by SgtPooki** [comment]
@BigLep @achingbrain IIUC, instructions for using this are now at https://github.com/ipfs/helia-delegated-routing-v1-http-api/blob/1db87c03a16b6fe91d6e851c0242d916c687afa9/packages/client/src/index.ts#L25-L40 which is copied automatically to the [README](https://github.com/ipfs/helia-delegated-routing-v1-http-api/blob/main/packages/client/README.md)

I don't believe we need [libp2p/js-http-v1-content-routing](https://github.com/libp2p/js-http-v1-content-routing) anymore since https://github.com/ipfs/helia-delegated-routing-v1-http-api/pull/44 was merged.

However, i think there are still some things that need addressed, because i'm having to patch this package in helia-http-gateway: https://github.com/ipfs/helia-http-gateway/pull/57/commits/ce971eb7acb61d2d38db62ce571bce89613a4026

**Comment by achingbrain** [comment]
Closing as I think all items here are complete.
